sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master
deploy:
  provider: heroku
  app: detect-changes
  api_key:
    secure: LKfsBgYYEeGHZ5Xwm5seYaykr0EyhUUuSrrU5ea8tC/k38XSwWq4Dx9DbijtdlNFSH0pPVB0PS/VuD+utgFVxT+W3CAHcTNEb5JNuuuRZ/O3I+YHkbudxZ46K6eH7CaGvKQVtktuSlxN42a3ZylQEUE6ykdXuZ0sDNfad7uKc79LnT1yYJ1R6YlJyy+q2ScyrtkkV9hUcIQtubj8Ke9XsfVE2JtZ3YnH4KHERzEw8KWJxc8FjaaA9yFbXIYkOmNfGdED1kS3K0JFIFcsfbkgHoq62bILv7Xxmk/LjvBdbfPYplBzHuVPZrmhrzOi1qTJ2gKz6Q7O5MWyQz775xlNsjlv79iZdKinsluko3eqJWbpAndts1dSJ/OdUU49ifIC6mBOtKXjqNhP9zVG83xbHZnUqkCAdG97LJrUYAUhkbmSs11sk+lCA5aTnwyoDQqKM7q/iKpAA/gGHyizVTpH0J8acJACsmDqlq/jrucQnhNI/3tVbZAY22EtIerY7uCeh0TjzazzXb4WgcLS8PcCaEao83iS/gtReI1siHs4NnMoQUhxayakdEQzr+UgR/eBwPRnS+e+zdpJlfNQaNiU2J4J1zcXu/YAIWaLX2M/Bm6OLzKKOq5iwtWWKZfyb4VgvrSz3jN3A9OgjmFVzFI4rm4bUpIbQJaycmzkGZsE9DA=
