sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master
deploy:
  provider: heroku
  app: detect-changes
  api_key:
    secure: iE5sBBWC/oyHx0kf8vmFXInx/bQBa/JTH9hE1zhwjf1drc8IIlFAceajfDqadhSqar6/DoHU+JlxcOXxYtmRjTcNDrelheQwam/cRFPbhD9DJ4k/9LFGCUPYDqqhoURSadi5/7HXGT/4qtQE0GYm6iUagJoGJS2LDzy2ZAYin0A2Nxdg9veAnloev1lnIKxCgyWsFwAGLKnOaZU5TDUvpkb9CQqX8LeLvkONq4bVMk7mSY5or3jbY7HHl4OCaWur9YxemoGe2q6Nk0LgpU4CiofpX4kqoM/KgiDaMP+UMWyB4wEezuvBqmYeI4cCrkBSR8ErAqTYWIrt5VrXzxOH//2j8BmNtiWoktNymVnrKz6lmNs1exBowZXge7OCBmXLOuyJYql+xk6wkQfbEp/f0rrbn1TQJ5a5XSLrGW4nyB9ZJWl6UcXnn+IlrtIk1mcX3/Rw5Rrt6G6mN72YJjxCcR8Pb7+RhxWI8LmCAvaMgFRv8+zR9OS+3SpZMPXPgCWFWjj3RfcNhzyxzX8tcuLlQKDPCWGbG/JrvNWAhsFs++TrCfTSZ6sYk/pX/UzIDw5IU16YkxbzOjiUAykJ1nPhHfL/ovsdN65Xs2rGXS+FknEYTFx75gjfmwwi9hvdLXE+9pkIU26FRKovt2rtWYD3e2T/zA8ElDeXnCI9yjg4yaQ=
