sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master
deploy:
  provider: heroku
  app: detect-changes
  api_key:
    secure: sTCoaAgVf9/27pR1Y6dtiq4EUZkuaEsp1h1ucwhugPlsa+QdE4sZag1OV894qiAfRtsG4nx7kYk4SvDjiCUIZibkzmVkwcmQ0LAihleU94Cl/FD6rzdGGGo4skoJ3gplksPQ0EionyiRHNk89z85+qttPu+m3Ko8230SzHgtZNHnTj2hervQnWDB9bjnpqBxECj4RK/5jhKup8+pkWt17w75W+ARvfOKuXRtO/zUViQ50KD3PPoqJxaUgYe75B2YgNifxHvy6oOJxwiHUWDwpJCqCrfkHL5Z58TaXFBXynL6sCeGWtofbbJxMD8cX5sIjplu8kTvq7nXVm5is577UPLwAE6VDJ4VEGr+m1z79kcI80Iky8XQ5q7pJibfucExlhwmFWoshD3C12pvrQ3EtfeZc5f72BKpQp5AHk91olyzGfBXw+/1Uza7kWdEXDTbjxEB+TS5yh/GnPJtauKjkVvyPdramrGiiG4OcvrIvhDUoyngJ5emghu+ahTZ84OowLz11N4HCHfYgtyjmXwS7031m3+rsVxDYsVio7HMBNjWQjd4+9RHTv1FW7bIktp6n0D5QuPBMJqFk5cO6F9PKo5y9o7vEoRWisr0zg+5gqKd2ar2BcB+cc2riQ3fWaSL8Y2zv18KRCaycgwKfDIvA9/i23QeGA/YCs0J4kMn+Qo=
